In [12]:
import sys
import pandas as pd

print(sys.executable)

c:\Users\SHREEJA\anaconda3\python.exe

In [2]:
import sys
!{sys.executable} -m pip install -U datasets

Requirement already satisfied: datasets in c:\users\shreeja\anaconda3\lib\site-packages (5.0.0)
Requirement already satisfied: filelock in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (2.3.5)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (1.19.0)
Requirement already satisfied: packaging in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\shreeja\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.10.0)
Requirement already satisfied: certifi in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\shreeja\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\shreeja\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\shreeja\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: colorama in c:\users\shreeja\anaconda3\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shreeja\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shreeja\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shreeja\anaconda3\lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\shreeja\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\shreeja\anaconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shreeja\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shreeja\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shreeja\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\shreeja\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
from datasets import load_dataset

dataset = load_dataset(
    "theatticusproject/cuad",
    verification_mode="no_checks"
)

print(dataset)

Resolving data files:   0%|          | 0/714 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['pdf'],
        num_rows: 511
    })
})

In [4]:
train_data = dataset["train"]

print(train_data.column_names)

['pdf']

In [5]:
import sys
!{sys.executable} -m pip install pdfplumber

Requirement already satisfied: pdfplumber in c:\users\shreeja\anaconda3\lib\site-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in c:\users\shreeja\anaconda3\lib\site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from pdfplumber) (12.2.0)
Requirement already satisfied: pypdfium2>=5.9.0 in c:\users\shreeja\anaconda3\lib\site-packages (from pdfplumber) (5.10.1)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from pdfminer.six==20260107->pdfplumber) (46.0.3)
Requirement already satisfied: cffi>=2.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in c:\users\shreeja\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.23)

In [6]:
sample = train_data[0]

print(sample.keys())

dict_keys(['pdf'])

In [7]:
sample

{'pdf': <pdfplumber.pdf.PDF at 0x1ab118682f0>}

In [8]:
train_data = dataset["train"]

print("Number of samples:", len(train_data))
print("\nColumns:")
print(train_data.column_names)

Number of samples: 511

Columns:
['pdf']

In [9]:
for key, value in sample.items():
    print("=" * 50)
    print("COLUMN:", key)
    print("TYPE:", type(value))
    print("VALUE:")
    print(str(value)[:500])
    print()

==================================================
COLUMN: pdf
TYPE: <class 'pdfplumber.pdf.PDF'>
VALUE:
<pdfplumber.pdf.PDF object at 0x000001AB118682F0>

In [10]:
for i in range(3):
    print("\n")
    print("=" * 80)
    print("SAMPLE", i)
    print("=" * 80)

    for key, value in train_data[i].items():
        print(f"\n{key}:")
        print(str(value)[:300])

================================================================================
SAMPLE 0
================================================================================

pdf:
<pdfplumber.pdf.PDF object at 0x000001AB119656D0>


================================================================================
SAMPLE 1
================================================================================

pdf:
<pdfplumber.pdf.PDF object at 0x000001AB0B8E2710>


================================================================================
SAMPLE 2
================================================================================

pdf:
<pdfplumber.pdf.PDF object at 0x000001AB119708A0>

In [13]:
df = pd.DataFrame(train_data[:10])

df.head()

                                                 pdf
0  <pdfplumber.pdf.PDF object at 0x000001AB11973A80>
1  <pdfplumber.pdf.PDF object at 0x000001AB119F6C30>
2  <pdfplumber.pdf.PDF object at 0x000001AB12090050>
3  <pdfplumber.pdf.PDF object at 0x000001AB12090490>
4  <pdfplumber.pdf.PDF object at 0x000001AB119B3950>

In [14]:
df = pd.DataFrame(train_data[:10])

df.head()

                                                 pdf
0  <pdfplumber.pdf.PDF object at 0x000001AB12084120>
1  <pdfplumber.pdf.PDF object at 0x000001AB11863E90>
2  <pdfplumber.pdf.PDF object at 0x000001AB12088290>
3  <pdfplumber.pdf.PDF object at 0x000001AB11A2FCD0>
4  <pdfplumber.pdf.PDF object at 0x000001AB120B8100>

In [15]:
with open("dataset_notes.txt", "w", encoding="utf-8") as f:
    f.write(f"Total Samples: {len(train_data)}\n")
    f.write(f"Columns: {train_data.column_names}\n")

print("Notes saved successfully.")

Notes saved successfully.

In [1]:
from datasets import load_dataset

dataset = load_dataset(
    "theatticusproject/cuad",
    verification_mode="no_checks"
)

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/714 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['pdf'],
        num_rows: 511
    })
})